USE [master]
GO
/****** Object:  Database [MusicLibrary]    Script Date: 2/14/2016 11:20:56 AM ******/
CREATE DATABASE [MusicLibrary] ON  PRIMARY 
( NAME = N'MusicLibrary', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\MusicLibrary.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MusicLibrary_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\MusicLibrary_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MusicLibrary].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MusicLibrary] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MusicLibrary] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MusicLibrary] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MusicLibrary] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MusicLibrary] SET ARITHABORT OFF 
GO
ALTER DATABASE [MusicLibrary] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MusicLibrary] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MusicLibrary] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MusicLibrary] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MusicLibrary] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MusicLibrary] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MusicLibrary] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MusicLibrary] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MusicLibrary] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MusicLibrary] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MusicLibrary] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MusicLibrary] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MusicLibrary] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MusicLibrary] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MusicLibrary] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MusicLibrary] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MusicLibrary] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MusicLibrary] SET RECOVERY FULL 
GO
ALTER DATABASE [MusicLibrary] SET  MULTI_USER 
GO
ALTER DATABASE [MusicLibrary] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MusicLibrary] SET DB_CHAINING OFF 
GO
USE [MusicLibrary]
GO
/****** Object:  Table [dbo].[Album]    Script Date: 2/14/2016 11:20:56 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Album](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ArtistId] [int] NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Year] [int] NOT NULL,
	[GenreId] [int] NOT NULL,
 CONSTRAINT [PK_Album] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Artist]    Script Date: 2/14/2016 11:20:56 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Artist](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Artist] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Genre]    Script Date: 2/14/2016 11:20:56 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Genre](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Genre] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Playlist]    Script Date: 2/14/2016 11:20:56 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Playlist](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Playlist] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Track]    Script Date: 2/14/2016 11:20:56 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Track](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[TrackNumber] [int] NOT NULL,
	[Length] [int] NULL,
 CONSTRAINT [PK_Track] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[xrAlbumGenre]    Script Date: 2/14/2016 11:20:56 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[xrAlbumGenre](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[GenreId] [int] NOT NULL,
	[AlbumId] [int] NOT NULL,
 CONSTRAINT [PK_xrAlbumGenre] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[xrAlbumTrack]    Script Date: 2/14/2016 11:20:56 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[xrAlbumTrack](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[AlbumId] [int] NOT NULL,
	[TrackId] [int] NOT NULL,
 CONSTRAINT [PK_xrAlbumTrack] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[xrPlaylistTrack]    Script Date: 2/14/2016 11:20:56 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[xrPlaylistTrack](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[PlaylistId] [int] NOT NULL,
	[TrackId] [int] NOT NULL,
 CONSTRAINT [PK_xrPlaylistTrack] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[Album]  WITH CHECK ADD  CONSTRAINT [FK_Album_Artist] FOREIGN KEY([ArtistId])
REFERENCES [dbo].[Artist] ([Id])
GO
ALTER TABLE [dbo].[Album] CHECK CONSTRAINT [FK_Album_Artist]
GO
ALTER TABLE [dbo].[Album]  WITH CHECK ADD  CONSTRAINT [FK_Album_Genre] FOREIGN KEY([GenreId])
REFERENCES [dbo].[Genre] ([Id])
GO
ALTER TABLE [dbo].[Album] CHECK CONSTRAINT [FK_Album_Genre]
GO
ALTER TABLE [dbo].[xrAlbumGenre]  WITH CHECK ADD  CONSTRAINT [FK_xrAlbumGenre_Album] FOREIGN KEY([AlbumId])
REFERENCES [dbo].[Album] ([Id])
GO
ALTER TABLE [dbo].[xrAlbumGenre] CHECK CONSTRAINT [FK_xrAlbumGenre_Album]
GO
ALTER TABLE [dbo].[xrAlbumGenre]  WITH CHECK ADD  CONSTRAINT [FK_xrAlbumGenre_Genre] FOREIGN KEY([GenreId])
REFERENCES [dbo].[Genre] ([Id])
GO
ALTER TABLE [dbo].[xrAlbumGenre] CHECK CONSTRAINT [FK_xrAlbumGenre_Genre]
GO
ALTER TABLE [dbo].[xrAlbumTrack]  WITH CHECK ADD  CONSTRAINT [FK_xrAlbumTrack_Album] FOREIGN KEY([AlbumId])
REFERENCES [dbo].[Album] ([Id])
GO
ALTER TABLE [dbo].[xrAlbumTrack] CHECK CONSTRAINT [FK_xrAlbumTrack_Album]
GO
ALTER TABLE [dbo].[xrAlbumTrack]  WITH CHECK ADD  CONSTRAINT [FK_xrAlbumTrack_Track] FOREIGN KEY([TrackId])
REFERENCES [dbo].[Track] ([Id])
GO
ALTER TABLE [dbo].[xrAlbumTrack] CHECK CONSTRAINT [FK_xrAlbumTrack_Track]
GO
ALTER TABLE [dbo].[xrPlaylistTrack]  WITH CHECK ADD  CONSTRAINT [FK_xrPlaylistTrack_Playlist] FOREIGN KEY([PlaylistId])
REFERENCES [dbo].[Playlist] ([Id])
GO
ALTER TABLE [dbo].[xrPlaylistTrack] CHECK CONSTRAINT [FK_xrPlaylistTrack_Playlist]
GO
ALTER TABLE [dbo].[xrPlaylistTrack]  WITH CHECK ADD  CONSTRAINT [FK_xrPlaylistTrack_Track] FOREIGN KEY([TrackId])
REFERENCES [dbo].[Track] ([Id])
GO
ALTER TABLE [dbo].[xrPlaylistTrack] CHECK CONSTRAINT [FK_xrPlaylistTrack_Track]
GO
USE [master]
GO
ALTER DATABASE [MusicLibrary] SET  READ_WRITE 
GO
